# Generated by Django 6.0.6 on 2026-06-08 21:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Morada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('license_number', models.CharField(blank=True, max_length=30, verbose_name='Carta de Condução')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='Cor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_companies', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Empresa de Entrega',
                'verbose_name_plural': 'Empresas de Entrega',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_stop', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8, verbose_name='Preço por Parada (€)')),
                ('price_per_pudo', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=8, verbose_name='Preço por PUDO (€)')),
                ('price_per_pickup', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=8, verbose_name='Preço por Recolha (€)')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_config', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Configuração de Tarifas',
                'verbose_name_plural': 'Configurações de Tarifas',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('trial', 'Período Experimental'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada')], default='trial', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gestor'), ('driver', 'Motorista')], default='manager', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stop_check.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizador',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('fuel_type', models.CharField(blank=True, max_length=30, verbose_name='Combustível')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['plate'],
                'unique_together': {('organization', 'plate')},
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Litros')),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Preço/Litro (€)')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('station', models.CharField(blank=True, max_length=100, verbose_name='Posto')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='stop_check.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='stop_check.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='stop_check.vehicle')),
            ],
            options={
                'verbose_name': 'Registo de Combustível',
                'verbose_name_plural': 'Registos de Combustível',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stop_check.expensecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='stop_check.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stop_check.vehicle')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_drivers', to='stop_check.vehicle'),
        ),
        migrations.CreateModel(
            name='DailyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('driver_stops', models.PositiveIntegerField(default=0, verbose_name='Paradas (Motorista)')),
                ('driver_pudo', models.PositiveIntegerField(default=0, verbose_name='PUDO (Motorista)')),
                ('driver_pickups', models.PositiveIntegerField(default=0, verbose_name='Recolhas (Motorista)')),
                ('company_stops', models.PositiveIntegerField(default=0, verbose_name='Paradas (Empresa)')),
                ('company_pudo', models.PositiveIntegerField(default=0, verbose_name='PUDO (Empresa)')),
                ('company_pickups', models.PositiveIntegerField(default=0, verbose_name='Recolhas (Empresa)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='stop_check.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='stop_check.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to='stop_check.vehicle')),
            ],
            options={
                'verbose_name': 'Comparação Diária',
                'verbose_name_plural': 'Comparações Diárias',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('organization', 'driver', 'date')},
            },
        ),
    ]
