# Generated by Django 6.0.6 on 2026-06-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0002_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verificação de Email',
                'verbose_name_plural': 'Verificações de Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
