# Generated by Django 6.0.6 on 2026-06-10 18:56

import django.db.models.deletion
from django.db import migrations, models


def populate_routes_from_comparisons(apps, schema_editor):
    DailyComparison = apps.get_model('stop_check', 'DailyComparison')
    Route = apps.get_model('stop_check', 'Route')
    Vehicle = apps.get_model('stop_check', 'Vehicle')
    Driver = apps.get_model('stop_check', 'Driver')

    for comp in DailyComparison.objects.filter(route__isnull=True).iterator():
        vehicle = comp.vehicle_id and Vehicle.objects.filter(pk=comp.vehicle_id).first()
        if not vehicle:
            driver = Driver.objects.filter(pk=comp.driver_id).first()
            if driver and driver.default_vehicle_id:
                vehicle = Vehicle.objects.filter(pk=driver.default_vehicle_id).first()
        if not vehicle:
            vehicle = Vehicle.objects.filter(
                organization_id=comp.organization_id, is_active=True
            ).first()
        if not vehicle:
            continue

        driver = Driver.objects.filter(pk=comp.driver_id).first()
        base_name = driver.name if driver else f'Rota {comp.driver_id}'
        name = base_name
        counter = 1
        while Route.objects.filter(
            organization_id=comp.organization_id,
            name=name,
            date=comp.date,
        ).exists():
            counter += 1
            name = f'{base_name} ({counter})'

        route = Route.objects.create(
            organization_id=comp.organization_id,
            name=name,
            date=comp.date,
            driver_id=comp.driver_id,
            vehicle_id=vehicle.pk,
        )
        comp.route_id = route.pk
        comp.save(update_fields=['route_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0003_emailverification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycomparison',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome / Código da Rota')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='stop_check.deliverycompany')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='stop_check.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='stop_check.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='stop_check.vehicle')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-date', 'name'],
                'unique_together': {('organization', 'name', 'date')},
            },
        ),
        migrations.AddField(
            model_name='dailycomparison',
            name='route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='stop_check.route'),
        ),
        migrations.AddField(
            model_name='stopevent',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_events', to='stop_check.route'),
        ),
        migrations.RunPython(populate_routes_from_comparisons, migrations.RunPython.noop),
    ]
