# Generated by Django 5.2.4 on 2026-06-12 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0004_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Atribuição de Rota', 'verbose_name_plural': 'Atribuições de Rota'},
        ),
        migrations.CreateModel(
            name='CompanyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome / Código da Rota')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_routes', to='stop_check.deliverycompany')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_routes', to='stop_check.organization')),
            ],
            options={
                'verbose_name': 'Rota da Empresa',
                'verbose_name_plural': 'Rotas da Empresa',
                'ordering': ['delivery_company__name', 'name'],
                'unique_together': {('organization', 'delivery_company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='company_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='stop_check.companyroute'),
        ),
    ]
