# Generated by Django 5.2.4 on 2026-06-12 18:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0006_populate_company_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyroute',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Diária (€)'),
        ),
        migrations.AddField(
            model_name='companyroute',
            name='price_per_pickup',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço por Recolha (€)'),
        ),
        migrations.AddField(
            model_name='companyroute',
            name='price_per_pudo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço por PUDO (€)'),
        ),
        migrations.AddField(
            model_name='companyroute',
            name='price_per_stop',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço por Parada (€)'),
        ),
    ]
