# Generated by Django 5.2.4 on 2026-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0008_copy_rates_to_company_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('gasoleo', 'Gasóleo'), ('gas_natural', 'Gás Natural'), ('eletrico', 'Elétrico')], max_length=20, verbose_name='Combustível'),
        ),
    ]
