# Generated by Django 5.2.4 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0009_vehicle_fuel_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycomparison',
            name='company_data_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('filled', 'Registado')], default='pending', max_length=20, verbose_name='Estado dados empresa'),
        ),
        migrations.AddField(
            model_name='dailycomparison',
            name='driver_data_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('filled', 'Registado')], default='pending', max_length=20, verbose_name='Estado dados motorista'),
        ),
    ]
