# Generated by Django 5.2.4 on 2026-06-24 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0020_driver_data_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyroute',
            name='pending_payment',
            field=models.BooleanField(default=False, help_text='Rota criada mas inactiva até confirmação do pagamento proporcional.', verbose_name='Aguarda pagamento'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do trial'),
        ),
        migrations.AddField(
            model_name='subscriptiontariff',
            name='included_routes',
            field=models.PositiveIntegerField(default=5, verbose_name='Rotas incluídas no plano base'),
        ),
        migrations.AddField(
            model_name='subscriptiontariff',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Dia do mês em que o pagamento deve ser efectuado (ex.: 5).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dia limite de pagamento'),
        ),
        migrations.AddField(
            model_name='subscriptiontariff',
            name='trial_days',
            field=models.PositiveIntegerField(default=31, verbose_name='Dias de trial'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stop_check.financialaccount', verbose_name='Plano de conta'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='subscriptiontariff',
            name='price_first_route',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Valor mensal que inclui o número de rotas definido acima.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Plano base (€/mês)'),
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('monthly', 'Mensalidade'), ('prorata_initial', 'Proporcional (contratação)'), ('prorata_route', 'Proporcional (rota adicional)')], max_length=20)),
                ('period_start', models.DateField(verbose_name='Início do período')),
                ('period_end', models.DateField(verbose_name='Fim do período')),
                ('route_count', models.PositiveIntegerField(default=1, verbose_name='Rotas facturadas')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (€)')),
                ('due_date', models.DateField(verbose_name='Data limite de pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Em atraso'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('payment_reported_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('company_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='stop_check.companyroute')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stop_check.subscription')),
            ],
            options={
                'verbose_name': 'Cobrança de Assinatura',
                'verbose_name_plural': 'Cobranças de Assinatura',
                'ordering': ['-period_start', '-generated_at'],
            },
        ),
    ]
