# Generated by Django 5.2.4 on 2026-06-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_check', '0022_backfill_trial_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_routes', models.PositiveIntegerField(verbose_name='Rotas adicionais solicitadas')),
                ('status', models.CharField(choices=[('pending', 'Aguarda pagamento'), ('paid', 'Pago — rotas liberadas'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_request', to='stop_check.subscriptioninvoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_requests', to='stop_check.subscription')),
            ],
            options={
                'verbose_name': 'Pedido de Rotas Adicionais',
                'verbose_name_plural': 'Pedidos de Rotas Adicionais',
                'ordering': ['-created_at'],
            },
        ),
    ]
